# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\user_interface.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(986, 569)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.formLayout = QtGui.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout.addWidget(self.lineEdit)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.verticalLayout.addWidget(self.comboBox)
        self.reload_schemas_button = QtGui.QPushButton(self.centralwidget)
        self.reload_schemas_button.setObjectName(_fromUtf8("reload_schemas_button"))
        self.verticalLayout.addWidget(self.reload_schemas_button)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.add_button = QtGui.QPushButton(self.centralwidget)
        self.add_button.setObjectName(_fromUtf8("add_button"))
        self.verticalLayout.addWidget(self.add_button)
        self.remove_button = QtGui.QPushButton(self.centralwidget)
        self.remove_button.setObjectName(_fromUtf8("remove_button"))
        self.verticalLayout.addWidget(self.remove_button)
        self.clea_button = QtGui.QPushButton(self.centralwidget)
        self.clea_button.setObjectName(_fromUtf8("clea_button"))
        self.verticalLayout.addWidget(self.clea_button)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.validate_all_button = QtGui.QPushButton(self.centralwidget)
        self.validate_all_button.setObjectName(_fromUtf8("validate_all_button"))
        self.verticalLayout.addWidget(self.validate_all_button)
        self.validate_selected_button = QtGui.QPushButton(self.centralwidget)
        self.validate_selected_button.setObjectName(_fromUtf8("validate_selected_button"))
        self.verticalLayout.addWidget(self.validate_selected_button)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.view_logs_button = QtGui.QPushButton(self.centralwidget)
        self.view_logs_button.setObjectName(_fromUtf8("view_logs_button"))
        self.verticalLayout.addWidget(self.view_logs_button)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout)
        self.table = QtGui.QTableWidget(self.centralwidget)
        self.table.setAlternatingRowColors(False)
        self.table.setWordWrap(True)
        self.table.setObjectName(_fromUtf8("table"))
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.table.horizontalHeader().setVisible(True)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setStretchLastSection(False)
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.table)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 986, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.label.setBuddy(self.comboBox)
        self.label_3.setBuddy(self.validate_all_button)
        self.label_4.setBuddy(self.view_logs_button)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Validator v1.0", None))
        self.label_5.setText(_translate("MainWindow", "Execution ID", None))
        self.label.setText(_translate("MainWindow", "Select Schema", None))
        self.reload_schemas_button.setText(_translate("MainWindow", "Reload Schemas", None))
        self.label_2.setText(_translate("MainWindow", "Add / Remove files", None))
        self.add_button.setText(_translate("MainWindow", "Add", None))
        self.remove_button.setText(_translate("MainWindow", "Remove", None))
        self.clea_button.setText(_translate("MainWindow", "Clear", None))
        self.label_3.setText(_translate("MainWindow", "Start Validation", None))
        self.validate_all_button.setText(_translate("MainWindow", "Validate All", None))
        self.validate_selected_button.setText(_translate("MainWindow", "Validate Selected", None))
        self.label_4.setText(_translate("MainWindow", "View Error Logs", None))
        self.view_logs_button.setText(_translate("MainWindow", "View Logs", None))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Select", None))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "File Name", None))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))

